// SPDX-License-Identifier: MIT
pragma solidity 0.8.26;

import "forge-std/Script.sol";
import "../src/AgentINFT.sol";
import "../src/Arena.sol";
import "../src/BreedingMarket.sol";
import "../src/RoyaltyVault.sol";

/// @title Deploy — Foundry deployment script for the AgentINFT ecosystem
/// @notice Deploys all four contracts in dependency order, wires them together,
///         and writes contract addresses to the shared TypeScript addresses file.
contract Deploy is Script {
    function run() external {
        uint256 deployerKey = vm.envUint("DEPLOYER_PRIVATE_KEY");
        address deployer    = vm.addr(deployerKey);

        vm.startBroadcast(deployerKey);

        // 1. Deploy AgentINFT
        AgentINFT agentINFT = new AgentINFT(deployer);
        console2.log("AgentINFT:", address(agentINFT));

        // 2. Deploy RoyaltyVault
        RoyaltyVault royaltyVault = new RoyaltyVault(deployer);
        console2.log("RoyaltyVault:", address(royaltyVault));

        // 3. Deploy Arena (references AgentINFT for ownership checks)
        Arena arena = new Arena(address(agentINFT), deployer);
        console2.log("Arena:", address(arena));

        // 4. Deploy BreedingMarket (references AgentINFT + RoyaltyVault)
        BreedingMarket breedingMarket = new BreedingMarket(
            address(agentINFT),
            address(royaltyVault),
            deployer
        );
        console2.log("BreedingMarket:", address(breedingMarket));

        // 5. Authorize Arena and BreedingMarket as AgentINFT minters
        agentINFT.addMinter(address(arena));
        agentINFT.addMinter(address(breedingMarket));
        console2.log("Authorized Arena and BreedingMarket as AgentINFT minters");

        // 6. Wire RoyaltyVault: grant BreedingMarket the right to register splits
        royaltyVault.setBreedingMarket(address(breedingMarket));
        console2.log("RoyaltyVault wired to BreedingMarket");

        vm.stopBroadcast();

        // 7. Write addresses to shared TypeScript file
        _writeAddresses(
            address(agentINFT),
            address(arena),
            address(breedingMarket),
            address(royaltyVault)
        );
    }

    function _writeAddresses(
        address agentINFT,
        address arena,
        address breedingMarket,
        address royaltyVault
    ) internal {
        string memory content = string.concat(
            "// AUTO-GENERATED by Deploy.s.sol - do not edit manually\n",
            "// Chain ID: ", vm.toString(block.chainid), "\n",
            "\n",
            "export const CONTRACT_ADDRESSES = {\n",
            "  AgentINFT:      \"", vm.toString(agentINFT),      "\" as const,\n",
            "  Arena:          \"", vm.toString(arena),          "\" as const,\n",
            "  BreedingMarket: \"", vm.toString(breedingMarket), "\" as const,\n",
            "  RoyaltyVault:   \"", vm.toString(royaltyVault),   "\" as const,\n",
            "} as const;\n",
            "\n",
            "export type ContractName = keyof typeof CONTRACT_ADDRESSES;\n"
        );

        vm.writeFile(
            "/Users/kamal/Desktop/ethglobal/packages/shared/src/addresses.ts",
            content
        );
        console2.log("Wrote addresses to packages/shared/src/addresses.ts");
    }
}
